# The name of the environment matching the repository name
name: Dimech_etAl_TL_ERT_db
channels:
- conda-forge
- defaults
dependencies:
- python>=3.7
- pip
- numpy
- pandas
- qgrid
- ipywidgets
- ipyleaflet
