# Use YAML for configuration since it allows comments like this
site_name: ERT TL database
description: A review on applications of time-lapse electrical resistivity tomography over the last 30 years perspectives for mining waste monitoring
author: Benjamin Mary
language: en
repository: BenjMy/ERT_TL_db
favicon: images/favicon.png
logo: images/nene-logo.svg
menu:
  - [Home, index]
  - [Map, map]  
  - [Table, dbtable]
ignore:
  - README.md
  - config-alternative.json
